# Generated by Django 4.1.7 on 2023-03-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default=0, max_length=25),
        ),
    ]
