# Generated by Django 4.1.7 on 2023-03-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=255),
        ),
    ]
